/**
 * Seed data constants — IDs from the OGS (Proving Grounds) set.
 * Auto-generated by generate-seed.ts — do not edit manually.
 */

// -- Set -----------------------------------------------------------------------

export const OGS_SET = {
  id: "019cfc3b-0369-76e1-8643-5310ac59ac33",
  slug: "OGS",
  name: "Proving Grounds",
} as const;

// -- Cards (all 24) -----------------------------------------------------------

export const CARDS = {
  "annie-fiery": {
    id: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    slug: "annie-fiery",
    name: "Annie, Fiery",
    type: "Unit",
    domains: ["Fury"],
  },
  "annie-stubborn": {
    id: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    slug: "annie-stubborn",
    name: "Annie, Stubborn",
    type: "Unit",
    domains: ["Chaos"],
  },
  "blast-of-power": {
    id: "019cfc3b-038a-7acd-8d1e-ff0cd42a7878",
    slug: "blast-of-power",
    name: "Blast of Power",
    type: "Spell",
    domains: ["Order"],
  },
  "dark-child-starter": {
    id: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    slug: "dark-child-starter",
    name: "Dark Child, Starter",
    type: "Legend",
    domains: ["Fury", "Chaos"],
  },
  "decisive-strike": {
    id: "019cfc3b-038b-7140-a819-397e9b1eb94e",
    slug: "decisive-strike",
    name: "Decisive Strike",
    type: "Spell",
    domains: ["Body", "Order"],
  },
  "final-spark": {
    id: "019cfc3b-038a-7c96-a595-49eecd42e4bf",
    slug: "final-spark",
    name: "Final Spark",
    type: "Spell",
    domains: ["Mind", "Order"],
  },
  firestorm: {
    id: "019cfc3b-038a-7e00-b828-03d838e5edab",
    slug: "firestorm",
    name: "Firestorm",
    type: "Spell",
    domains: ["Fury"],
  },
  flash: {
    id: "019cfc3b-038a-7e2f-a482-917692bfd498",
    slug: "flash",
    name: "Flash",
    type: "Spell",
    domains: ["Chaos"],
  },
  "fury-rune": {
    id: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    slug: "fury-rune",
    name: "Fury Rune",
    type: "Rune",
    domains: ["Fury"],
  },
  "garen-commander": {
    id: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    slug: "garen-commander",
    name: "Garen, Commander",
    type: "Unit",
    domains: ["Order"],
  },
  "garen-rugged": {
    id: "019cfc3b-038a-7c30-8616-613222ef6b01",
    slug: "garen-rugged",
    name: "Garen, Rugged",
    type: "Unit",
    domains: ["Body"],
  },
  "gentlemen-s-duel": {
    id: "019cfc3b-038a-7e20-b240-25edfa53cbca",
    slug: "gentlemen-s-duel",
    name: "Gentlemen's Duel",
    type: "Spell",
    domains: ["Body"],
  },
  highlander: {
    id: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    slug: "highlander",
    name: "Highlander",
    type: "Spell",
    domains: ["Calm", "Body"],
  },
  incinerate: {
    id: "019cfc3b-0389-7de9-8860-226f4c8947d8",
    slug: "incinerate",
    name: "Incinerate",
    type: "Spell",
    domains: ["Fury"],
  },
  "lady-of-luminosity-starter": {
    id: "019cfc3b-038a-7aff-9f64-d915ada7e046",
    slug: "lady-of-luminosity-starter",
    name: "Lady of Luminosity, Starter",
    type: "Legend",
    domains: ["Mind", "Order"],
  },
  "lux-crownguard": {
    id: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    slug: "lux-crownguard",
    name: "Lux, Crownguard",
    type: "Unit",
    domains: ["Order"],
  },
  "lux-illuminated": {
    id: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    slug: "lux-illuminated",
    name: "Lux, Illuminated",
    type: "Unit",
    domains: ["Mind"],
  },
  "master-yi-honed": {
    id: "019cfc3b-038a-7abc-b43e-79b55463b059",
    slug: "master-yi-honed",
    name: "Master Yi, Honed",
    type: "Unit",
    domains: ["Body"],
  },
  "master-yi-meditative": {
    id: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    slug: "master-yi-meditative",
    name: "Master Yi, Meditative",
    type: "Unit",
    domains: ["Calm"],
  },
  "might-of-demacia-starter": {
    id: "019cfc3b-038a-7e76-9ea8-f1feb5c9d837",
    slug: "might-of-demacia-starter",
    name: "Might of Demacia, Starter",
    type: "Legend",
    domains: ["Body", "Order"],
  },
  "recruit-the-vanguard": {
    id: "019cfc3b-038a-7add-b48d-e16b7614dfda",
    slug: "recruit-the-vanguard",
    name: "Recruit the Vanguard",
    type: "Spell",
    domains: ["Order"],
  },
  tibbers: {
    id: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    slug: "tibbers",
    name: "Tibbers",
    type: "Unit",
    domains: ["Fury", "Chaos"],
  },
  "vanguard-attendant": {
    id: "019cfc3b-038a-7c63-a32a-d4ca63b2bee9",
    slug: "vanguard-attendant",
    name: "Vanguard Attendant",
    type: "Unit",
    domains: ["Order"],
  },
  "wuju-bladesman-starter": {
    id: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    slug: "wuju-bladesman-starter",
    name: "Wuju Bladesman, Starter",
    type: "Legend",
    domains: ["Calm", "Body"],
  },
  "zephyr-sage": {
    id: "019cfc3b-038a-7e10-b8d4-6e8b9646a975",
    slug: "zephyr-sage",
    name: "Zephyr Sage",
    type: "Unit",
    domains: ["Calm"],
  },
} as const;

// -- Printings (all 24) -------------------------------------------------------

export const PRINTINGS = {
  "OGN-007:common:normal::ZH": {
    id: "019d69a5-28fa-70a2-92ea-73d8f2a27d3f",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Common",
    finish: "normal",
  },
  "OGN-007:common:normal::EN": {
    id: "019cfc3b-03d2-75a9-b281-305c0ec46c9c",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Common",
    finish: "normal",
  },
  "OGN-007a:showcase:foil::ZH": {
    id: "019d69a4-8117-73d6-9aec-69530d59d8da",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "OGN-007a:showcase:foil::EN": {
    id: "019cfc3b-03d1-7eb9-b5d5-588deb7bd4a7",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "OGN-007b:showcase:foil:promo:EN": {
    id: "019cfde8-86d5-734d-add4-3f4fc05c1173",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "OGN-007b:showcase:foil::ZH": {
    id: "019d69a4-f7b9-7222-bb93-cb745d47be9f",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "OGS-001:epic:foil:nexus:EN": {
    id: "019d17a1-2723-733a-a21e-4630e4370046",
    cardId: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-001:epic:normal::EN": {
    id: "019cfc3b-03d6-74cf-adec-1dce41f631eb",
    cardId: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-001:epic:normal::ZH": {
    id: "019d6d05-930d-7af7-9eb5-1bbefadba3a4",
    cardId: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-002:uncommon:normal::ZH": {
    id: "019d6d05-9935-76e8-a805-ea6541cb99dd",
    cardId: "019cfc3b-038a-7e00-b828-03d838e5edab",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-002:uncommon:normal::EN": {
    id: "019cfc3b-03d5-768e-91cf-8ac59b20fb0e",
    cardId: "019cfc3b-038a-7e00-b828-03d838e5edab",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-003:common:normal::ZH": {
    id: "019d6d05-9a7a-7234-aa16-3d519c8131c9",
    cardId: "019cfc3b-0389-7de9-8860-226f4c8947d8",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-003:common:normal::EN": {
    id: "019cfc3b-03d6-74e0-bdbe-4aca898a0bbd",
    cardId: "019cfc3b-0389-7de9-8860-226f4c8947d8",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-004:rare:foil:nexus:EN": {
    id: "019d17a6-13f6-74f3-bcaa-6974580b57db",
    cardId: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-004:rare:normal::ZH": {
    id: "019d6d05-a758-7fce-aadd-aafcc11baebe",
    cardId: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-004:rare:normal::EN": {
    id: "019cfc3b-03d6-74f2-bcff-7bd89d0061f5",
    cardId: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-005:uncommon:normal::ZH": {
    id: "019d6d05-aa97-77be-8913-cae20a56f25f",
    cardId: "019cfc3b-038a-7e10-b8d4-6e8b9646a975",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-005:uncommon:normal::EN": {
    id: "019cfc3b-03d6-7502-b5c1-a9e422f91ac7",
    cardId: "019cfc3b-038a-7e10-b8d4-6e8b9646a975",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-006:rare:normal::ZH": {
    id: "019d6d05-b0ac-79e3-8edc-0d6d436d148b",
    cardId: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-006:rare:normal::EN": {
    id: "019cfc3b-03d6-7514-9347-be4597ff1eee",
    cardId: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-006:rare:foil:nexus:EN": {
    id: "019d1be8-3681-73b5-bf13-078b7e3c9096",
    cardId: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-007:rare:normal::EN": {
    id: "019cfc3b-03d6-752a-adc5-19033009d65d",
    cardId: "019cfc3b-038a-7c30-8616-613222ef6b01",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-007:rare:normal::ZH": {
    id: "019d6d05-b656-79e4-b3df-2c0c6414f64b",
    cardId: "019cfc3b-038a-7c30-8616-613222ef6b01",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-007:rare:foil:nexus:EN": {
    id: "019d1bee-0857-793a-b76b-50b6ead8ddbb",
    cardId: "019cfc3b-038a-7c30-8616-613222ef6b01",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-008:common:normal::EN": {
    id: "019cfc3b-03d6-753c-9ec3-7cf48219b1e8",
    cardId: "019cfc3b-038a-7e20-b240-25edfa53cbca",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-008:common:normal::ZH": {
    id: "019d6d05-b99e-7e0e-96dd-e1c9da4bdae3",
    cardId: "019cfc3b-038a-7e20-b240-25edfa53cbca",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-009:epic:normal::EN": {
    id: "019cfc3b-03d6-754e-a4de-ca223b302965",
    cardId: "019cfc3b-038a-7abc-b43e-79b55463b059",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-009:epic:normal::ZH": {
    id: "019d6d05-c13a-799a-bda0-efd70a6a1b75",
    cardId: "019cfc3b-038a-7abc-b43e-79b55463b059",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-009:epic:foil:nexus:EN": {
    id: "019d17ac-724a-732c-b83a-23cd257a74e5",
    cardId: "019cfc3b-038a-7abc-b43e-79b55463b059",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-010:rare:foil:nexus:EN": {
    id: "019d1bf8-97d5-79ac-929e-286838af5508",
    cardId: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-010:rare:normal::EN": {
    id: "019cfc3b-03d6-755e-8d42-32464c0bf236",
    cardId: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-010:rare:normal::ZH": {
    id: "019d6d05-c823-7069-95b6-1cdf23f82a9a",
    cardId: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-011:common:normal::ZH": {
    id: "019d6d05-d8e2-7e53-8fe6-54fd10424a8b",
    cardId: "019cfc3b-038a-7e2f-a482-917692bfd498",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-011:common:normal::EN": {
    id: "019cfc3b-03d6-7570-ac57-ad240fe24183",
    cardId: "019cfc3b-038a-7e2f-a482-917692bfd498",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-012:common:normal::ZH": {
    id: "019d6d05-d9e8-75ca-9545-64d46c8fb6cb",
    cardId: "019cfc3b-038a-7acd-8d1e-ff0cd42a7878",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-012:common:normal::EN": {
    id: "019cfc3b-03d6-7581-bf1d-f627860d73b0",
    cardId: "019cfc3b-038a-7acd-8d1e-ff0cd42a7878",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-013:epic:normal::ZH": {
    id: "019d6d05-e5d5-7c5b-8b55-90aeb47adb3e",
    cardId: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-013:epic:foil:nexus:EN": {
    id: "019d1bfd-da4c-73d9-b2c9-a6c628b23bdd",
    cardId: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-013:epic:normal::EN": {
    id: "019cfc3b-03d6-7592-be7d-af8b5a85a818",
    cardId: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-014:epic:foil:nexus:EN": {
    id: "019d1c00-e58f-73c9-a402-a822d45df1f9",
    cardId: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-014:epic:normal::EN": {
    id: "019cfc3b-03d6-75a3-90b8-c82d7afdc00a",
    cardId: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-014:epic:normal::ZH": {
    id: "019d6d05-f9be-789f-b21f-bfe68b1572d8",
    cardId: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-015:uncommon:normal::EN": {
    id: "019cfc3b-03d6-75d8-a0f7-c6fd8a35c6f9",
    cardId: "019cfc3b-038a-7add-b48d-e16b7614dfda",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-015:uncommon:normal::ZH": {
    id: "019d6d05-fee6-7d60-b8f2-ea216d891c59",
    cardId: "019cfc3b-038a-7add-b48d-e16b7614dfda",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-016:common:normal::EN": {
    id: "019cfc3b-03d6-75ee-922c-1e736369b5d4",
    cardId: "019cfc3b-038a-7c63-a32a-d4ca63b2bee9",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-016:common:normal::ZH": {
    id: "019d6d06-0398-7088-8098-0484a6aa2fea",
    cardId: "019cfc3b-038a-7c63-a32a-d4ca63b2bee9",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-017:rare:foil:nexus:EN": {
    id: "019d1c05-bf03-747d-be95-60ee1687b24b",
    cardId: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-017:rare:normal::ZH": {
    id: "019d6d06-108e-726f-809e-13b31796be1c",
    cardId: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-017:rare:normal::EN": {
    id: "019cfc3b-03d6-7600-9bd2-f43441e40ace",
    cardId: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-018:epic:normal::ZH": {
    id: "019d6d06-1dd2-7649-938a-01851a1098ae",
    cardId: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-018:epic:normal::EN": {
    id: "019cfc3b-03d8-7309-9eae-0ba9ba5967f3",
    cardId: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-018:epic:foil:nexus:EN": {
    id: "019d1c0b-64ab-7160-8bd6-36dfdffb1210",
    cardId: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-019:rare:foil:nexus:EN": {
    id: "019d1c0e-5395-709b-a44a-b9b9bc85907b",
    cardId: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-019:rare:normal::ZH": {
    id: "019d6d06-2149-7ed5-a52b-64215640186a",
    cardId: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-019:rare:normal::EN": {
    id: "019cfc3b-03d8-731c-8957-4f2dc4f8464f",
    cardId: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-020:epic:foil:nexus:EN": {
    id: "019d1c11-4999-78e3-9980-2298b44d436d",
    cardId: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-020:epic:normal::ZH": {
    id: "019d6d06-2210-7187-b6ea-5d10e2e048ab",
    cardId: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-020:epic:normal::EN": {
    id: "019cfc3b-03d8-732e-9d55-1e74ebff11dd",
    cardId: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-021:rare:normal::ZH": {
    id: "019d6d06-3071-78cb-871f-945422034de3",
    cardId: "019cfc3b-038a-7aff-9f64-d915ada7e046",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-021:rare:normal::EN": {
    id: "019cfc3b-03d8-7340-8664-d8b5b646ef84",
    cardId: "019cfc3b-038a-7aff-9f64-d915ada7e046",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-022:epic:normal::ZH": {
    id: "019d6d06-31c7-75c2-ba60-479deb454553",
    cardId: "019cfc3b-038a-7c96-a595-49eecd42e4bf",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-022:epic:normal::EN": {
    id: "019cfc3b-03d8-7350-b433-2aee587b1912",
    cardId: "019cfc3b-038a-7c96-a595-49eecd42e4bf",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-023:rare:normal::ZH": {
    id: "019d6d06-3485-71cd-bcef-9c7db6924832",
    cardId: "019cfc3b-038a-7e76-9ea8-f1feb5c9d837",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-023:rare:normal::EN": {
    id: "019cfc3b-03d8-7361-9a9a-915783d54e1c",
    cardId: "019cfc3b-038a-7e76-9ea8-f1feb5c9d837",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-024:epic:normal::EN": {
    id: "019cfc3b-03d8-7371-9e2d-f3aa5ad324a9",
    cardId: "019cfc3b-038b-7140-a819-397e9b1eb94e",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-024:epic:normal::ZH": {
    id: "019d6d06-37a3-7312-bb34-9c497b8b9d64",
    cardId: "019cfc3b-038b-7140-a819-397e9b1eb94e",
    rarity: "Epic",
    finish: "normal",
  },
  "SFD-R01:common:normal::EN": {
    id: "019cfded-5ed2-7f73-80a1-9cfea07679c8",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Common",
    finish: "normal",
  },
  "SFD-R01:common:normal::ZH": {
    id: "019d69a5-bdd0-7753-98b2-253827e5d3b5",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Common",
    finish: "normal",
  },
  "SFD-R01a:showcase:foil::ZH": {
    id: "019d69a5-8576-7b4d-9c18-7aa1f4451540",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "SFD-R01a:showcase:foil::EN": {
    id: "019cfdee-854c-7472-b74c-3a33a8485cea",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "SFD-R01b:showcase:foil:promo:EN": {
    id: "019cfdf0-6c9d-76f1-ab80-f96bc3670fb0",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "SFD-R01b:showcase:foil::ZH": {
    id: "019d69a5-e53a-7e57-886d-a4524d3da4f8",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
  "UNL-R01a:showcase:foil::EN": {
    id: "019cfde9-e3e5-7af6-ad98-b9fcc2bfd125",
    cardId: "019cfc3b-0387-7b61-be7a-edfadddd1879",
    rarity: "Showcase",
    finish: "foil",
  },
} as const;

// -- Convenience aliases for common test needs --------------------------------
//
// These are keyed by the current kebab-case card slug. Card slugs derive from
// the card name, so they can change if a card is renamed. When that happens,
// update the key on the right-hand side after regenerating.

/** A Unit card in the Fury domain (Epic rarity): Annie, Fiery */
export const CARD_FURY_UNIT = CARDS["annie-fiery"];
/** A Spell card in the Fury domain (Uncommon rarity): Firestorm */
export const CARD_FURY_SPELL = CARDS["firestorm"];
/** A Unit card in the Calm domain (Rare rarity): Master Yi, Meditative */
export const CARD_CALM_UNIT = CARDS["master-yi-meditative"];
/** A Unit card in the Body domain (Rare rarity): Garen, Rugged */
export const CARD_BODY_UNIT = CARDS["garen-rugged"];
/** A Unit card in the Mind domain (Rare rarity): Lux, Illuminated */
export const CARD_MIND_UNIT = CARDS["lux-illuminated"];
/** A Unit card in the Order domain (Epic rarity): Garen, Commander */
export const CARD_ORDER_UNIT = CARDS["garen-commander"];

/** Printing for OGS-001 (Epic, normal finish, EN): Annie, Fiery */
export const PRINTING_1 = PRINTINGS["OGS-001:epic:normal::EN"];
/** Printing for OGS-002 (Uncommon, normal finish, EN): Firestorm */
export const PRINTING_2 = PRINTINGS["OGS-002:uncommon:normal::EN"];
/** Printing for OGS-003 (Common, normal finish, EN): Incinerate */
export const PRINTING_3 = PRINTINGS["OGS-003:common:normal::EN"];
/** Printing for OGS-004 (Rare, normal finish, EN): Master Yi, Meditative */
export const PRINTING_4 = PRINTINGS["OGS-004:rare:normal::EN"];

// -- Marketplace groups -------------------------------------------------------

export const MARKETPLACE_GROUPS = {
  cardmarket_6286: {
    id: "019cfc3a-e5d3-7e7e-9497-23ee0c612850",
    marketplace: "cardmarket",
    groupId: 6286,
    name: "Origins",
  },
  cardmarket_6289: {
    id: "019cfc3a-e5d3-7e90-b462-c8bed1bf05f2",
    marketplace: "cardmarket",
    groupId: 6289,
    name: "Proving Grounds",
  },
  cardmarket_6322: {
    id: "019cfc3a-e5d3-7ea2-a7ed-d1d82f6cdea5",
    marketplace: "cardmarket",
    groupId: 6322,
    name: "Origins: Promos",
  },
  cardmarket_6399: {
    id: "019cfc3a-e5d3-7eb3-abad-5fdffa803665",
    marketplace: "cardmarket",
    groupId: 6399,
    name: "Spiritforged",
  },
  cardmarket_6480: {
    id: "019cfc3a-e5d3-7ec3-9543-f9f44e5915aa",
    marketplace: "cardmarket",
    groupId: 6480,
    name: "Project K Promos",
  },
  cardmarket_6483: {
    id: "019cfc3a-e5d3-7ed4-8999-3cd4b463f244",
    marketplace: "cardmarket",
    groupId: 6483,
    name: "Spiritforged: Promos",
  },
  cardtrader_4166: {
    id: "019d1c29-9066-737b-8946-b9e3101587c1",
    marketplace: "cardtrader",
    groupId: 4166,
    name: "Origins",
  },
  cardtrader_4167: {
    id: "019d1c29-9068-7cbc-882a-e1bcbf146596",
    marketplace: "cardtrader",
    groupId: 4167,
    name: "Promos",
  },
  cardtrader_4275: {
    id: "019d1c29-9069-7097-8252-8f3be7d4ade1",
    marketplace: "cardtrader",
    groupId: 4275,
    name: "Origins Proving Grounds",
  },
  cardtrader_4287: {
    id: "019d1c29-9069-7229-ad09-cb5eb07466c1",
    marketplace: "cardtrader",
    groupId: 4287,
    name: "Organized Play",
  },
  cardtrader_4288: {
    id: "019d1c29-9069-747a-beab-1570e3ab757b",
    marketplace: "cardtrader",
    groupId: 4288,
    name: "Judge Promos",
  },
  cardtrader_4289: {
    id: "019d1c29-9069-764c-b786-082f8c1a9840",
    marketplace: "cardtrader",
    groupId: 4289,
    name: "Arcane",
  },
  cardtrader_4299: {
    id: "019d1c29-9069-77ae-83a8-bd64449d8a9b",
    marketplace: "cardtrader",
    groupId: 4299,
    name: "Spiritforged",
  },
  cardtrader_4347: {
    id: "019d1c29-9069-7912-abde-0f84f7a0fea8",
    marketplace: "cardtrader",
    groupId: 4347,
    name: "Championship Promo",
  },
  cardtrader_4348: {
    id: "019d1c29-9069-7a79-be25-ad6ad9d2d51d",
    marketplace: "cardtrader",
    groupId: 4348,
    name: "Nexus Night Promos",
  },
  cardtrader_4349: {
    id: "019d1c29-9069-7c84-b27c-5a9bbc8498aa",
    marketplace: "cardtrader",
    groupId: 4349,
    name: "Release Event Promos",
  },
  cardtrader_4425: {
    id: "019d1c29-906a-704f-8628-feed96f41172",
    marketplace: "cardtrader",
    groupId: 4425,
    name: "Unleashed",
  },
  cardtrader_4521: {
    id: "019d1c29-906a-726f-a12f-f13b745fd5fc",
    marketplace: "cardtrader",
    groupId: 4521,
    name: "Vendetta",
  },
  cardtrader_4522: {
    id: "019d1c29-906a-74ea-b28f-1c2b80c38ccb",
    marketplace: "cardtrader",
    groupId: 4522,
    name: "Radiance",
  },
  tcgplayer_24343: {
    id: "019cfc3a-e5d3-7e5b-8dd3-6cd925320b27",
    marketplace: "tcgplayer",
    groupId: 24_343,
    name: "Riftbound Promotional Cards",
  },
  tcgplayer_24344: {
    id: "019cfc3a-e5d3-7e27-a1bc-c57dea97644a",
    marketplace: "tcgplayer",
    groupId: 24_344,
    name: "Origins",
  },
  tcgplayer_24439: {
    id: "019cfc3a-e5d3-7e38-8af3-07d1e517947c",
    marketplace: "tcgplayer",
    groupId: 24_439,
    name: "Origins: Proving Grounds",
  },
  tcgplayer_24502: {
    id: "019cfc3a-e5d3-7e6d-ad96-f51fdb4d70ba",
    marketplace: "tcgplayer",
    groupId: 24_502,
    name: "Riftbound Worlds Bundle 2025",
  },
  tcgplayer_24519: {
    id: "019cfc3a-e5d3-7df3-838e-550f1a2fd90a",
    marketplace: "tcgplayer",
    groupId: 24_519,
    name: "Spiritforged",
  },
  tcgplayer_24528: {
    id: "019cfc3a-e5d3-7e4a-bc91-dd70fab6d75c",
    marketplace: "tcgplayer",
    groupId: 24_528,
    name: "Riftbound Organized Play Promotional Cards",
  },
  tcgplayer_24552: {
    id: "019cfc3a-e5d3-7e15-8287-881760ec56ed",
    marketplace: "tcgplayer",
    groupId: 24_552,
    name: "Riftbound Judge Promotional Cards",
  },
  tcgplayer_24560: {
    id: "019cfc3a-e5d3-7c3d-96c9-dc5f89f12fba",
    marketplace: "tcgplayer",
    groupId: 24_560,
    name: "Unleashed",
  },
} as const;

/** TCGPlayer group for OGS */
export const TCGPLAYER_OGS_GROUP = MARKETPLACE_GROUPS["tcgplayer_24439"];
/** Cardmarket group for OGS */
export const CARDMARKET_OGS_GROUP = MARKETPLACE_GROUPS["cardmarket_6289"];

// -- Synthetic errata and bans ------------------------------------------------

/** Card with synthetic errata: Annie, Fiery */
export const ERRATA_CARD = CARDS["annie-fiery"];
/** Card with synthetic ban: Blast of Power */
export const BANNED_CARD = CARDS["blast-of-power"];
/** Format used for the synthetic ban */
export const BAN_FORMAT_ID = "freeform";
