/**
 * Generates seed.sql and constants.ts from the local development database.
 *
 * Run manually after schema changes:
 *   bun run apps/api/src/test/fixtures/generate-seed.ts
 *
 * Requires DATABASE_URL to be set (reads from ../../.env automatically).
 */

// oxlint-disable-next-line import/no-nodejs-modules -- CLI script, not a browser module
import { writeFileSync } from "node:fs";
// oxlint-disable-next-line import/no-nodejs-modules -- CLI script, not a browser module
import { resolve } from "node:path";

import postgres from "postgres";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error(
    "DATABASE_URL is not set. Run with: bun --env-file=../../.env run src/test/fixtures/generate-seed.ts",
  );
  process.exit(1);
}

const sql = postgres(DATABASE_URL);

const SET_SLUG = "OGS"; // Proving Grounds — smallest set, 24 cards

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeValue(v: unknown): string {
  if (v === null || v === undefined) {
    return "NULL";
  }
  if (typeof v === "boolean") {
    return v ? "TRUE" : "FALSE";
  }
  if (typeof v === "number") {
    return String(v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return "'{}'";
    }
    return `'{${v.map((e) => `"${String(e).replaceAll('"', String.raw`\"`)}"`).join(",")}}'`;
  }
  const s = String(v).replaceAll("'", "''");
  return `'${s}'`;
}

function toInsert(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) {
    return "";
  }
  const cols = Object.keys(rows[0]);
  const header = `INSERT INTO ${table} (${cols.join(", ")}) VALUES`;
  const values = rows.map((r) => `  (${cols.map((c) => escapeValue(r[c])).join(", ")})`);
  return `${header}\n${values.join(",\n")};\n`;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

console.log(`Querying ${SET_SLUG} data from local DB...`);

const sets = await sql<Record<string, unknown>[]>`
  SELECT id, slug, name, printed_total, sort_order, released_at
  FROM sets WHERE slug = ${SET_SLUG}
`;

const cards = await sql<Record<string, unknown>[]>`
  SELECT DISTINCT c.id, c.slug, c.name, c.type, c.super_types, c.domains,
    c.might, c.energy, c.power, c.might_bonus, c.keywords,
    c.rules_text, c.effect_text, c.tags, c.norm_name
  FROM cards c
  JOIN printings p ON p.card_id = c.id
  JOIN sets s ON s.id = p.set_id
  WHERE s.slug = ${SET_SLUG}
  ORDER BY c.slug
`;

const printings = await sql<Record<string, unknown>[]>`
  SELECT p.id, p.card_id, p.set_id, p.short_code, p.collector_number, p.rarity,
    p.art_variant, p.is_signed, p.is_promo, p.finish, p.artist, p.public_code,
    p.printed_rules_text, p.printed_effect_text, p.flavor_text, p.slug, p.comment
  FROM printings p
  JOIN sets s ON s.id = p.set_id
  WHERE s.slug = ${SET_SLUG}
  ORDER BY p.collector_number
`;

const marketplaceGroups = await sql<Record<string, unknown>[]>`
  SELECT id, marketplace, group_id, name, abbreviation
  FROM marketplace_groups
  ORDER BY marketplace, group_id
`;

const marketplaceSources = await sql<Record<string, unknown>[]>`
  SELECT ms.id, ms.marketplace, ms.group_id, ms.external_id, ms.product_name, ms.printing_id
  FROM marketplace_products ms
  JOIN printings p ON p.id = ms.printing_id
  JOIN sets s ON s.id = p.set_id
  WHERE s.slug = ${SET_SLUG}
  ORDER BY ms.marketplace, ms.external_id
`;

const cardNameAliases = await sql<Record<string, unknown>[]>`
  SELECT DISTINCT cna.card_id, cna.norm_name
  FROM card_name_aliases cna
  JOIN cards c ON c.id = cna.card_id
  JOIN printings p ON p.card_id = c.id
  JOIN sets s ON s.id = p.set_id
  WHERE s.slug = ${SET_SLUG}
  ORDER BY cna.card_id
`;

await sql.end();

// ---------------------------------------------------------------------------
// Generate seed.sql
// ---------------------------------------------------------------------------

const seedSql = [
  "-- Auto-generated by generate-seed.ts — do not edit manually.",
  `-- Source: local DB, set ${SET_SLUG} (${sets[0]?.name})`,
  `-- Generated: ${new Date().toISOString()}`,
  "",
  toInsert("sets", sets),
  toInsert("cards", cards),
  toInsert("printings", printings),
  toInsert("marketplace_groups", marketplaceGroups),
  toInsert("marketplace_products", marketplaceSources),
  toInsert("card_name_aliases", cardNameAliases),
].join("\n");

// oxlint-disable-next-line typescript/no-non-null-assertion -- dirname is always defined when running as a script
const dir = resolve(import.meta.dirname!);
writeFileSync(resolve(dir, "seed.sql"), seedSql);
console.log(
  `Wrote seed.sql (${sets.length} sets, ${cards.length} cards, ${printings.length} printings, ${marketplaceGroups.length} marketplace groups, ${marketplaceSources.length} marketplace sources, ${cardNameAliases.length} aliases)`,
);

// ---------------------------------------------------------------------------
// Generate constants.ts
// ---------------------------------------------------------------------------

interface PrintingRow {
  id: string;
  slug: string;
  card_id: string;
  collector_number: number;
  rarity: string;
  finish: string;
}

interface CardRow {
  id: string;
  slug: string;
  name: string;
  type: string;
  domains: string[];
}

const typedPrintings = printings as unknown as PrintingRow[];
const typedCards = cards as unknown as CardRow[];

const constantsTs = `/**
 * Seed data constants — IDs from the OGS (Proving Grounds) set.
 * Auto-generated by generate-seed.ts — do not edit manually.
 */

// -- Set -----------------------------------------------------------------------

export const OGS_SET = {
  id: ${JSON.stringify(sets[0]?.id)},
  slug: "OGS",
  name: "Proving Grounds",
} as const;

// -- Cards (all 24) -----------------------------------------------------------

export const CARDS = {
${typedCards
  .map(
    (c) =>
      `  ${JSON.stringify(c.slug)}: { id: ${JSON.stringify(c.id)}, slug: ${JSON.stringify(c.slug)}, name: ${JSON.stringify(c.name)}, type: ${JSON.stringify(c.type)}, domains: ${JSON.stringify(c.domains)} },`,
  )
  .join("\n")}
} as const;

// -- Printings (all 24) -------------------------------------------------------

export const PRINTINGS = {
${typedPrintings
  .map(
    (p) =>
      `  ${JSON.stringify(p.slug)}: { id: ${JSON.stringify(p.id)}, cardId: ${JSON.stringify(p.card_id)}, rarity: ${JSON.stringify(p.rarity)}, finish: ${JSON.stringify(p.finish)} },`,
  )
  .join("\n")}
} as const;

// -- Convenience aliases for common test needs --------------------------------

/** A Unit card in the Fury domain (Epic rarity) */
export const CARD_FURY_UNIT = CARDS["OGS-001"];
/** A Spell card in the Fury domain (Uncommon rarity) */
export const CARD_FURY_SPELL = CARDS["OGS-002"];
/** A Unit card in the Calm domain (Rare rarity) */
export const CARD_CALM_UNIT = CARDS["OGS-004"];
/** A Unit card in the Body domain (Rare rarity) */
export const CARD_BODY_UNIT = CARDS["OGS-007"];
/** A Unit card in the Mind domain (Rare rarity) */
export const CARD_MIND_UNIT = CARDS["OGS-006"];
/** A Unit card in the Order domain (Epic rarity) */
export const CARD_ORDER_UNIT = CARDS["OGS-013"];

/** Printing for OGS-001 (Epic, normal finish) */
export const PRINTING_1 = PRINTINGS["OGS-001:epic:normal:"];
/** Printing for OGS-002 (Uncommon, normal finish) */
export const PRINTING_2 = PRINTINGS["OGS-002:uncommon:normal:"];
/** Printing for OGS-003 (Common, normal finish) */
export const PRINTING_3 = PRINTINGS["OGS-003:common:normal:"];
/** Printing for OGS-004 (Rare, normal finish) */
export const PRINTING_4 = PRINTINGS["OGS-004:rare:normal:"];

// -- Marketplace groups -------------------------------------------------------

export const MARKETPLACE_GROUPS = {
${marketplaceGroups
  .map(
    (g: Record<string, unknown>) =>
      `  "${g.marketplace}_${g.group_id}": { id: ${JSON.stringify(g.id)}, marketplace: ${JSON.stringify(g.marketplace)}, groupId: ${g.group_id}, name: ${JSON.stringify(g.name)} },`,
  )
  .join("\n")}
} as const;

/** TCGPlayer group for OGS */
export const TCGPLAYER_OGS_GROUP = MARKETPLACE_GROUPS["tcgplayer_24439"];
/** Cardmarket group for OGS */
export const CARDMARKET_OGS_GROUP = MARKETPLACE_GROUPS["cardmarket_6289"];
`;

writeFileSync(resolve(dir, "constants.ts"), constantsTs);
console.log("Wrote constants.ts");

console.log("Done!");
