// Re-export all table types from the local tables file (single source of truth).
export type {
  ActivitiesTable,
  ActivityItemsTable,
  CardNameAliasesTable,
  CardSourcesTable,
  CardsTable,
  CollectionsTable,
  CopiesTable,
  Database,
  DeckCardsTable,
  DecksTable,
  FeatureFlagsTable,
  MarketplaceGroupsTable,
  MarketplaceIgnoredProductsTable,
  MarketplaceSnapshotsTable,
  MarketplaceSourcesTable,
  MarketplaceStagingCardOverridesTable,
  MarketplaceStagingTable,
  PrintingImagesTable,
  PrintingSourcesTable,
  PrintingsTable,
  Readable,
  SessionsTable,
  SetsTable,
  SourcesTable,
  TradeListItemsTable,
  TradeListsTable,
  UsersTable,
  VerificationsTable,
  WishListItemsTable,
  WishListsTable,
} from "./tables.js";
