// Re-export all table types from the local tables file (single source of truth).
export type {
  AcquisitionSourcesTable,
  ActivitiesTable,
  ActivityItemsTable,
  CandidateCardsTable,
  CandidatePrintingsTable,
  CardNameAliasesTable,
  CardsTable,
  CollectionsTable,
  CopiesTable,
  Database,
  DeckCardsTable,
  DecksTable,
  FeatureFlagsTable,
  IgnoredCandidateCardsTable,
  IgnoredCandidatePrintingsTable,
  KeywordStylesTable,
  MarketplaceProductsTable,
  MarketplaceSnapshotsTable,
  PrintingImagesTable,
  PrintingsTable,
  SetsTable,
  TradeListItemsTable,
  TradeListsTable,
  WishListItemsTable,
  WishListsTable,
} from "./tables.js";
