/**
 * Image variants generated by the rehost service. Each name is the on-disk
 * suffix used in the filename (e.g. `-120w.webp`).
 *
 * Pick a variant by the slot's CSS pixel width × DPR — `120w` covers slots up
 * to ~60px CSS at DPR 2, `240w` up to ~120px, `400w` up to ~200px, `full` is
 * the 800w short-edge canonical size for the detail-page hero.
 */
export type ImageVariant = "120w" | "240w" | "400w" | "full";

/**
 * Build the public URL for a card image variant from its `image_files.id`.
 * The directory prefix is the last 2 hex chars of the UUID — the same scheme
 * the rehoster uses on disk.
 *
 * @returns `/media/cards/{prefix}/{imageId}-{variant}.webp`
 */
export function imageUrl(imageId: string, variant: ImageVariant): string {
  return `/media/cards/${imageId.slice(-2)}/${imageId}-${variant}.webp`;
}
