import type { DeckFormat, DeckResponse, DeckZone, Printing } from "@openrift/shared";
import { useDebouncedValue } from "@tanstack/react-pacer";
import { useQuery } from "@tanstack/react-query";
import { createLazyFileRoute, useNavigate } from "@tanstack/react-router";
import {
  AlertTriangleIcon,
  CheckCircle2Icon,
  ChevronDownIcon,
  ChevronRightIcon,
  Loader2Icon,
  SearchIcon,
  UploadIcon,
  XCircleIcon,
} from "lucide-react";
import { useId, useRef, useState } from "react";
import { toast } from "sonner";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useCards } from "@/hooks/use-cards";
import { deckDetailQueryOptions, useCreateDeck, useSaveDeckCards } from "@/hooks/use-decks";
import { useZoneOrder } from "@/hooks/use-enums";
import type { DeckMatchStatus, DeckMatchedEntry, ResolvedCard } from "@/lib/deck-import-matcher";
import { matchDeckEntries } from "@/lib/deck-import-matcher";
import type { DeckImportFormat } from "@/lib/deck-import-parsers";
import { parseDeckImportData } from "@/lib/deck-import-parsers";
import { cn } from "@/lib/utils";

export const Route = createLazyFileRoute("/_app/_authenticated/decks/import")({
  component: DeckImportPage,
});

const STATUS_SORT_ORDER: Record<DeckMatchStatus, number> = {
  exact: 0,
  "needs-review": 1,
  unresolved: 2,
};

/** @returns Display name for sorting purposes. */
function entryDisplayName(entry: DeckMatchedEntry): string {
  return (
    entry.resolvedCard?.cardName ??
    entry.entry.cardName ??
    entry.entry.shortCode ??
    ""
  ).toLowerCase();
}

type ImportStep = "input" | "preview";

const DECK_FORMAT_LABELS: Record<string, string> = {
  constructed: "Constructed",
  freeform: "Freeform",
};

const IMPORT_PLACEHOLDERS: Record<DeckImportFormat, string> = {
  piltover: "Paste a Piltover Archive deck code...",
  text: "Legend:\n1 Card Name\n\nMainDeck:\n3 Card Name\n...",
  tts: "OGN-001-1 OGN-002-1 OGN-003-1 ...",
};

const IMPORT_DESCRIPTIONS: Record<DeckImportFormat, React.ReactNode> = {
  piltover: (
    <>
      A compact code generated by{" "}
      <a
        href="https://piltoverarchive.com"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Piltover Archive
      </a>
      . Copy it from the deck builder&apos;s share/export button.
    </>
  ),
  text: (
    <>
      A plain text list with optional zone headers like &quot;Legend:&quot; or
      &quot;MainDeck:&quot;. One card per line as &quot;quantity name&quot;. Without zone headers,
      cards are sorted into zones automatically based on their type. Used by many deck builders,
      including{" "}
      <a
        href="https://piltoverarchive.com"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Piltover Archive
      </a>{" "}
      and{" "}
      <a
        href="https://tcg-arena.fr/decks"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        TCG Arena
      </a>
      .
    </>
  ),
  tts: (
    <>
      A space-separated list of short codes (e.g. OGN-001) used by the{" "}
      <a
        href="https://steamcommunity.com/sharedfiles/filedetails/?id=3606647746"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Tabletop Simulator mod
      </a>
      .
    </>
  ),
};

function DeckImportPage() {
  const { replaceDeckId } = Route.useSearch();
  const { allPrintings } = useCards();
  const { zoneOrder, zoneLabels } = useZoneOrder();
  const createDeck = useCreateDeck();
  const saveDeckCards = useSaveDeckCards();
  const navigate = useNavigate();

  const replaceDeckQuery = useQuery({
    ...deckDetailQueryOptions(replaceDeckId ?? ""),
    enabled: Boolean(replaceDeckId),
  });
  const replaceDeckName = replaceDeckQuery.data?.deck.name;
  const isReplaceMode = Boolean(replaceDeckId);

  const [step, setStep] = useState<ImportStep>("input");
  const [rawText, setRawText] = useState("");
  const [importFormat, setImportFormat] = useState<DeckImportFormat>("piltover");
  const [deckName, setDeckName] = useState("Imported Deck");
  const [deckFormat, setDeckFormat] = useState<DeckFormat>("constructed");
  const [matchedEntries, setMatchedEntries] = useState<DeckMatchedEntry[]>([]);
  const [parseWarnings, setParseWarnings] = useState<string[]>([]);
  const [skippedIndices, setSkippedIndices] = useState<Set<number>>(new Set());
  const [expandedIndices, setExpandedIndices] = useState<Set<number>>(new Set());
  const [isImporting, setIsImporting] = useState(false);
  const [confirmReplaceOpen, setConfirmReplaceOpen] = useState(false);

  const handleParse = (text: string) => {
    const { entries, warnings } = parseDeckImportData(text, importFormat);
    setParseWarnings(warnings);

    if (entries.length === 0) {
      return;
    }

    const matched = matchDeckEntries(entries, allPrintings);
    const zoneIndex = Object.fromEntries(zoneOrder.map((slug, index) => [slug, index]));
    const sorted = matched.toSorted((entryA, entryB) => {
      const zoneDiff = (zoneIndex[entryA.zone] ?? 99) - (zoneIndex[entryB.zone] ?? 99);
      if (zoneDiff !== 0) {
        return zoneDiff;
      }
      const nameA = entryDisplayName(entryA);
      const nameB = entryDisplayName(entryB);
      if (nameA !== nameB) {
        return nameA.localeCompare(nameB);
      }
      return STATUS_SORT_ORDER[entryA.status] - STATUS_SORT_ORDER[entryB.status];
    });
    setMatchedEntries(sorted);
    setSkippedIndices(new Set());

    // Auto-expand non-exact entries so the user sees what needs attention
    const nonExact = new Set<number>();
    for (let index = 0; index < sorted.length; index++) {
      if (sorted[index].status !== "exact") {
        nonExact.add(index);
      }
    }
    setExpandedIndices(nonExact);

    setStep("preview");
  };

  const handleResolve = (index: number, card: ResolvedCard) => {
    setMatchedEntries((prev) =>
      prev.map((entry, entryIndex) =>
        entryIndex === index
          ? {
              ...entry,
              resolvedCard: card,
              status: "exact" as DeckMatchStatus,
              zone: entry.entry.explicitZone ?? entry.zone,
            }
          : entry,
      ),
    );
  };

  const handleZoneChange = (index: number, zone: DeckZone) => {
    setMatchedEntries((prev) =>
      prev.map((entry, entryIndex) => (entryIndex === index ? { ...entry, zone } : entry)),
    );
  };

  const handleSkip = (index: number) => {
    setSkippedIndices((prev) => new Set([...prev, index]));
  };

  const handleUnskip = (index: number) => {
    setSkippedIndices((prev) => {
      const next = new Set(prev);
      next.delete(index);
      return next;
    });
  };

  const handleToggleExpand = (index: number) => {
    setExpandedIndices((prev) => {
      const next = new Set(prev);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  };

  const readyEntries = matchedEntries.filter(
    (entry, index) => entry.resolvedCard && !skippedIndices.has(index),
  );
  const needsAttention = matchedEntries.filter(
    (entry, index) => !entry.resolvedCard && !skippedIndices.has(index),
  );
  const skippedCount = skippedIndices.size;
  const totalCards = readyEntries.reduce((sum, entry) => sum + entry.entry.quantity, 0);

  const buildCards = () => {
    // Group by cardId + zone + preferredPrintingId, summing quantities.
    // Printing-specific matches (piltover/tts short codes) become distinct
    // rows from any default-art rows of the same card.
    const cardMap = new Map<
      string,
      { cardId: string; zone: DeckZone; quantity: number; preferredPrintingId: string | null }
    >();
    for (const entry of readyEntries) {
      if (!entry.resolvedCard) {
        continue;
      }
      const preferredPrintingId = entry.resolvedCard.preferredPrintingId;
      const key = `${entry.resolvedCard.cardId}::${entry.zone}::${preferredPrintingId ?? ""}`;
      const existing = cardMap.get(key);
      if (existing) {
        existing.quantity += entry.entry.quantity;
      } else {
        cardMap.set(key, {
          cardId: entry.resolvedCard.cardId,
          zone: entry.zone,
          quantity: entry.entry.quantity,
          preferredPrintingId,
        });
      }
    }
    return [...cardMap.values()];
  };

  const executeReplace = () => {
    if (!replaceDeckId) {
      return;
    }
    const targetName = replaceDeckName ?? "deck";
    setIsImporting(true);
    saveDeckCards.mutate(
      { deckId: replaceDeckId, cards: buildCards() },
      {
        onSuccess: () => {
          toast.success(`Replaced cards in "${targetName}" with ${totalCards} cards.`);
          void navigate({ to: "/decks/$deckId", params: { deckId: replaceDeckId } });
        },
        onError: () => {
          toast.error("Failed to replace deck cards.");
          setIsImporting(false);
        },
      },
    );
  };

  const executeCreate = () => {
    const trimmedName = deckName.trim();
    if (!trimmedName) {
      toast.error("Please enter a deck name.");
      return;
    }

    setIsImporting(true);
    const cards = buildCards();

    createDeck.mutate(
      { name: trimmedName, format: deckFormat },
      {
        onSuccess: (data) => {
          const deck = data as DeckResponse;
          saveDeckCards.mutate(
            { deckId: deck.id, cards },
            {
              onSuccess: () => {
                toast.success(`Imported deck "${trimmedName}" with ${totalCards} cards.`);
                void navigate({ to: "/decks/$deckId", params: { deckId: deck.id } });
              },
              onError: () => {
                toast.error("Failed to save deck cards.");
                setIsImporting(false);
              },
            },
          );
        },
        onError: () => {
          toast.error("Failed to create deck.");
          setIsImporting(false);
        },
      },
    );
  };

  const handleImport = () => {
    if (isReplaceMode) {
      setConfirmReplaceOpen(true);
      return;
    }
    executeCreate();
  };

  if (step === "input") {
    return (
      <InputStep
        rawText={rawText}
        onTextChange={setRawText}
        importFormat={importFormat}
        onImportFormatChange={setImportFormat}
        onParse={handleParse}
        parseWarnings={parseWarnings}
        replaceDeckName={isReplaceMode ? (replaceDeckName ?? "") : undefined}
      />
    );
  }

  return (
    <>
      <PreviewStep
        matchedEntries={matchedEntries}
        allPrintings={allPrintings}
        parseWarnings={parseWarnings}
        skippedIndices={skippedIndices}
        expandedIndices={expandedIndices}
        deckName={deckName}
        deckFormat={deckFormat}
        zoneOrder={zoneOrder}
        zoneLabels={zoneLabels}
        readyCount={readyEntries.length}
        needsAttentionCount={needsAttention.length}
        skippedCount={skippedCount}
        totalCards={totalCards}
        isImporting={isImporting}
        replaceDeckName={isReplaceMode ? (replaceDeckName ?? "") : undefined}
        onResolve={handleResolve}
        onZoneChange={handleZoneChange}
        onSkip={handleSkip}
        onUnskip={handleUnskip}
        onToggleExpand={handleToggleExpand}
        onDeckNameChange={setDeckName}
        onDeckFormatChange={setDeckFormat}
        onImport={handleImport}
        onBack={() => setStep("input")}
      />
      <AlertDialog open={confirmReplaceOpen} onOpenChange={setConfirmReplaceOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Replace deck contents?</AlertDialogTitle>
            <AlertDialogDescription>
              This will remove all existing cards in &ldquo;{replaceDeckName ?? "this deck"}&rdquo;
              and replace them with the {totalCards} imported {totalCards === 1 ? "card" : "cards"}.
              The deck&apos;s name and format are kept.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={() => {
                setConfirmReplaceOpen(false);
                executeReplace();
              }}
            >
              Replace
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

// ---------------------------------------------------------------------------
// Step 1: Input
// ---------------------------------------------------------------------------

function InputStep({
  rawText,
  onTextChange,
  importFormat,
  onImportFormatChange,
  onParse,
  parseWarnings,
  replaceDeckName,
}: {
  rawText: string;
  onTextChange: (text: string) => void;
  importFormat: DeckImportFormat;
  onImportFormatChange: (format: DeckImportFormat) => void;
  onParse: (text: string) => void;
  parseWarnings: string[];
  replaceDeckName?: string;
}) {
  const isReplaceMode = replaceDeckName !== undefined;
  return (
    <div className="mx-auto max-w-2xl space-y-6 px-4 py-6">
      <div>
        <h2 className="text-lg font-semibold">
          {isReplaceMode ? "Replace deck contents" : "Import Deck"}
        </h2>
        <p className="text-muted-foreground text-sm">
          {isReplaceMode ? (
            <>
              Paste a deck code, text list, or TTS string to replace the cards in
              {replaceDeckName ? (
                <>
                  {" "}
                  <strong className="text-foreground">&ldquo;{replaceDeckName}&rdquo;</strong>
                </>
              ) : (
                " this deck"
              )}
              . The deck&apos;s name and format are kept.
            </>
          ) : (
            <>
              Paste a deck code, text list, or TTS string to import a deck. Want another format
              supported?{" "}
              <a
                href="https://github.com/eikowagenknecht/openrift/issues"
                target="_blank"
                rel="noreferrer"
                className="text-foreground underline"
              >
                Open a GitHub issue
              </a>
              .
            </>
          )}
        </p>
      </div>

      <Tabs
        value={importFormat}
        onValueChange={(value) => onImportFormatChange(value as DeckImportFormat)}
      >
        <TabsList>
          <TabsTrigger value="piltover">Deck Code</TabsTrigger>
          <TabsTrigger value="text">Text</TabsTrigger>
          <TabsTrigger value="tts">TTS</TabsTrigger>
        </TabsList>

        <TabsContent value={importFormat}>
          <div className="space-y-3">
            <p className="text-muted-foreground text-sm">{IMPORT_DESCRIPTIONS[importFormat]}</p>
            <Textarea
              value={rawText}
              onChange={(event) => onTextChange(event.target.value)}
              placeholder={IMPORT_PLACEHOLDERS[importFormat]}
              className={cn(
                "font-mono text-xs",
                importFormat === "piltover" ? "min-h-[120px]" : "min-h-[320px]",
              )}
            />

            <div className="flex items-center gap-3">
              <Button onClick={() => onParse(rawText)} disabled={rawText.trim().length === 0}>
                <UploadIcon className="mr-2 size-4" />
                Parse
              </Button>
            </div>
          </div>
        </TabsContent>
      </Tabs>

      {parseWarnings.length > 0 && (
        <div className="rounded-md border border-red-200 bg-red-50 p-3 dark:border-red-900 dark:bg-red-950">
          {parseWarnings.map((warning) => (
            <p key={warning} className="text-sm text-red-700 dark:text-red-400">
              {warning}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 2: Preview
// ---------------------------------------------------------------------------

function PreviewStep({
  matchedEntries,
  allPrintings,
  parseWarnings,
  skippedIndices,
  expandedIndices,
  deckName,
  deckFormat,
  zoneOrder,
  zoneLabels,
  readyCount,
  needsAttentionCount,
  skippedCount,
  totalCards,
  isImporting,
  replaceDeckName,
  onResolve,
  onZoneChange,
  onSkip,
  onUnskip,
  onToggleExpand,
  onDeckNameChange,
  onDeckFormatChange,
  onImport,
  onBack,
}: {
  matchedEntries: DeckMatchedEntry[];
  allPrintings: Printing[];
  parseWarnings: string[];
  skippedIndices: Set<number>;
  expandedIndices: Set<number>;
  deckName: string;
  deckFormat: DeckFormat;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  readyCount: number;
  needsAttentionCount: number;
  skippedCount: number;
  totalCards: number;
  isImporting: boolean;
  replaceDeckName?: string;
  onResolve: (index: number, card: ResolvedCard) => void;
  onZoneChange: (index: number, zone: DeckZone) => void;
  onSkip: (index: number) => void;
  onUnskip: (index: number) => void;
  onToggleExpand: (index: number) => void;
  onDeckNameChange: (name: string) => void;
  onDeckFormatChange: (format: DeckFormat) => void;
  onImport: () => void;
  onBack: () => void;
}) {
  const isReplaceMode = replaceDeckName !== undefined;
  const canImport = readyCount > 0 && (isReplaceMode || deckName.trim().length > 0);

  return (
    <div className="mx-auto max-w-3xl space-y-4 px-4 py-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">
            {isReplaceMode ? "Replace Preview" : "Import Preview"}
          </h2>
          <p className="text-muted-foreground text-sm">
            {matchedEntries.length} card{matchedEntries.length === 1 ? "" : "s"} parsed
            {isReplaceMode && replaceDeckName ? (
              <>
                {" "}
                — replacing contents of{" "}
                <strong className="text-foreground">&ldquo;{replaceDeckName}&rdquo;</strong>
              </>
            ) : null}
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={onBack}>
          Back
        </Button>
      </div>

      {/* Entry list */}
      <div className="divide-border divide-y rounded-md border">
        {matchedEntries.map((entry, index) => (
          <DeckImportEntryRow
            key={`${entry.entry.shortCode ?? entry.entry.cardName ?? ""}-${entry.zone}-${index}`}
            entry={entry}
            allPrintings={allPrintings}
            index={index}
            zoneOrder={zoneOrder}
            zoneLabels={zoneLabels}
            isSkipped={skippedIndices.has(index)}
            isExpanded={expandedIndices.has(index)}
            onResolve={onResolve}
            onZoneChange={onZoneChange}
            onSkip={onSkip}
            onUnskip={onUnskip}
            onToggleExpand={onToggleExpand}
          />
        ))}
      </div>

      {/* Parse warnings */}
      {parseWarnings.length > 0 && (
        <div className="rounded-md border border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950">
          <p className="px-3 py-2 font-medium text-amber-800 dark:text-amber-300">
            {parseWarnings.length} warning{parseWarnings.length === 1 ? "" : "s"} while parsing
          </p>
          <div className="space-y-1 border-t border-amber-200 px-3 py-2 dark:border-amber-900">
            {parseWarnings.map((warning) => (
              <p key={warning} className="text-amber-700 dark:text-amber-400">
                {warning}
              </p>
            ))}
          </div>
        </div>
      )}

      {/* Summary + deck options + import button */}
      <div className="bg-muted/50 space-y-4 rounded-md border p-4">
        <div className="flex flex-wrap items-center gap-2 text-sm">
          <Badge variant="secondary">{readyCount} ready</Badge>
          {needsAttentionCount > 0 && (
            <Badge variant="default">{needsAttentionCount} need attention</Badge>
          )}
          {skippedCount > 0 && <Badge variant="ghost">{skippedCount} skipped</Badge>}
        </div>

        {needsAttentionCount > 0 && (
          <p className="text-muted-foreground text-sm">
            Having trouble importing?{" "}
            <a
              href="https://github.com/eikowagenknecht/openrift/issues"
              target="_blank"
              rel="noreferrer"
              className="text-foreground underline"
            >
              Open a GitHub issue
            </a>{" "}
            and we&apos;ll take a look.
          </p>
        )}

        <div className="flex flex-wrap items-end gap-3">
          {!isReplaceMode && (
            <>
              <div className="space-y-1.5">
                <Label htmlFor="preview-deck-name">Deck name</Label>
                <Input
                  id="preview-deck-name"
                  value={deckName}
                  onChange={(event) => onDeckNameChange(event.target.value)}
                  className="w-[200px]"
                />
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="preview-deck-format">Format</Label>
                <Select
                  value={deckFormat}
                  onValueChange={(value) => onDeckFormatChange(value as DeckFormat)}
                >
                  <SelectTrigger id="preview-deck-format" className="mb-0 w-[140px]">
                    <SelectValue>
                      {(value: string) => DECK_FORMAT_LABELS[value] ?? value}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="constructed">Constructed</SelectItem>
                    <SelectItem value="freeform">Freeform</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </>
          )}

          <Button
            variant={isReplaceMode ? "destructive" : "default"}
            onClick={onImport}
            disabled={!canImport || isImporting}
          >
            {isImporting ? (
              <>
                <Loader2Icon className="mr-2 size-4 animate-spin" />
                {isReplaceMode ? "Replacing..." : "Importing..."}
              </>
            ) : isReplaceMode ? (
              <>
                Replace with {totalCards} {totalCards === 1 ? "card" : "cards"}
              </>
            ) : (
              <>
                Import {totalCards} {totalCards === 1 ? "card" : "cards"}
              </>
            )}
          </Button>
          {needsAttentionCount > 0 && !isImporting && (
            <span className="text-muted-foreground text-sm">
              (skips {needsAttentionCount} unmatched)
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Single entry row
// ---------------------------------------------------------------------------

const STATUS_CONFIG: Record<DeckMatchStatus, { icon: React.ElementType; className: string }> = {
  exact: { icon: CheckCircle2Icon, className: "text-emerald-600 dark:text-emerald-400" },
  "needs-review": { icon: AlertTriangleIcon, className: "text-amber-600 dark:text-amber-400" },
  unresolved: { icon: XCircleIcon, className: "text-red-600 dark:text-red-400" },
};

function DeckImportEntryRow({
  entry,
  allPrintings,
  index,
  zoneOrder,
  zoneLabels,
  isSkipped,
  isExpanded,
  onResolve,
  onZoneChange,
  onSkip,
  onUnskip,
  onToggleExpand,
}: {
  entry: DeckMatchedEntry;
  allPrintings: Printing[];
  index: number;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  isSkipped: boolean;
  isExpanded: boolean;
  onResolve: (index: number, card: ResolvedCard) => void;
  onZoneChange: (index: number, zone: DeckZone) => void;
  onSkip: (index: number) => void;
  onUnskip: (index: number) => void;
  onToggleExpand: (index: number) => void;
}) {
  const [showSearch, setShowSearch] = useState(false);
  const { icon: StatusIcon, className: statusColor } = STATUS_CONFIG[entry.status];
  const ChevronIcon = isExpanded ? ChevronDownIcon : ChevronRightIcon;
  const rawFieldEntries = Object.entries(entry.entry.rawFields);
  const displayName =
    entry.resolvedCard?.cardName ?? entry.entry.cardName ?? entry.entry.shortCode ?? "Unknown";

  return (
    <div className={cn(isSkipped && "opacity-40")}>
      <div className="flex items-center gap-3 px-4 py-2.5 text-sm">
        <button
          type="button"
          className="text-muted-foreground hover:text-foreground shrink-0"
          onClick={() => onToggleExpand(index)}
        >
          <ChevronIcon className="size-4" />
        </button>

        <StatusIcon className={cn("size-4 shrink-0", statusColor)} />

        <span className="text-muted-foreground w-10 shrink-0 text-right tabular-nums">
          {entry.entry.quantity}&times;
        </span>

        {entry.entry.shortCode && (
          <span className="text-muted-foreground shrink-0 text-xs">{entry.entry.shortCode}</span>
        )}

        <span className="min-w-0 flex-1 truncate font-medium">
          {displayName}
          <span className="text-muted-foreground ml-1.5 text-xs font-normal">
            {zoneLabels[entry.zone]}
          </span>
        </span>

        <div className="flex shrink-0 items-center gap-2">
          {entry.suggestedName && (
            <span className="text-muted-foreground text-xs">
              Did you mean <em>{entry.suggestedName}</em>?
            </span>
          )}

          {showSearch ? (
            <CardSearch
              allPrintings={allPrintings}
              onSelect={(card) => {
                onResolve(index, card);
                setShowSearch(false);
              }}
            />
          ) : null}

          <Button
            variant="ghost"
            size="xs"
            onClick={() => setShowSearch(!showSearch)}
            aria-label={showSearch ? "Close search" : "Search catalog"}
          >
            {showSearch ? (
              <XCircleIcon className="size-3.5" />
            ) : (
              <SearchIcon className="size-3.5" />
            )}
          </Button>

          <ZonePicker
            zone={entry.zone}
            zoneOrder={zoneOrder}
            zoneLabels={zoneLabels}
            onZoneChange={(zone) => onZoneChange(index, zone)}
          />

          {isSkipped ? (
            <Button variant="ghost" size="xs" onClick={() => onUnskip(index)}>
              Unskip
            </Button>
          ) : (
            <Button variant="ghost" size="xs" onClick={() => onSkip(index)}>
              Skip
            </Button>
          )}
        </div>
      </div>

      {isExpanded && rawFieldEntries.length > 0 && (
        <div className="bg-muted/30 border-border border-t px-4 py-2">
          <div className="flex flex-wrap gap-x-5 gap-y-1 text-xs">
            {rawFieldEntries.map(([key, value]) => (
              <div key={key}>
                <span className="text-muted-foreground">{key}: </span>
                <span>{value}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Zone picker
// ---------------------------------------------------------------------------

function ZonePicker({
  zone,
  zoneOrder,
  zoneLabels,
  onZoneChange,
}: {
  zone: DeckZone;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  onZoneChange: (zone: DeckZone) => void;
}) {
  // Overflow is not user-assignable
  const assignableZones = zoneOrder.filter((zoneSlug) => zoneSlug !== "overflow");

  return (
    <Select
      value={zone}
      onValueChange={(value) => onZoneChange(value as DeckZone)}
      items={Object.fromEntries(assignableZones.map((zoneKey) => [zoneKey, zoneLabels[zoneKey]]))}
    >
      <SelectTrigger size="sm" className="h-7 w-auto text-xs">
        <SelectValue />
      </SelectTrigger>
      <SelectContent className="w-auto">
        {assignableZones.map((zoneKey) => (
          <SelectItem key={zoneKey} value={zoneKey} className="py-1.5">
            {zoneLabels[zoneKey]}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// ---------------------------------------------------------------------------
// Card search (for correction UI)
// ---------------------------------------------------------------------------

function CardSearch({
  allPrintings,
  onSelect,
}: {
  allPrintings: Printing[];
  onSelect: (card: ResolvedCard) => void;
}) {
  const [search, setSearch] = useState("");
  const [showResults, setShowResults] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);
  const containerRef = useRef<HTMLDivElement>(null);
  const listRef = useRef<HTMLDivElement>(null);
  const listboxId = useId();
  const [debouncedSearch] = useDebouncedValue(search, { wait: 150 });

  // Deduplicate to unique cards (not printings)
  const results =
    debouncedSearch.length >= 2
      ? deduplicateToCards(allPrintings, debouncedSearch).slice(0, 20)
      : [];

  const visible = showResults && search.length >= 2;
  const activeOptionId = activeIndex >= 0 ? `${listboxId}-option-${activeIndex}` : undefined;

  function scrollActiveIntoView(index: number) {
    const item = listRef.current?.children[index] as HTMLElement | undefined;
    if (item) {
      item.scrollIntoView({ block: "nearest" });
    }
  }

  function handleKeyDown(event: React.KeyboardEvent) {
    if (!visible || results.length === 0) {
      return;
    }

    switch (event.key) {
      case "ArrowDown": {
        event.preventDefault();
        const next = activeIndex < results.length - 1 ? activeIndex + 1 : 0;
        setActiveIndex(next);
        scrollActiveIntoView(next);
        break;
      }
      case "ArrowUp": {
        event.preventDefault();
        const prev = activeIndex > 0 ? activeIndex - 1 : results.length - 1;
        setActiveIndex(prev);
        scrollActiveIntoView(prev);
        break;
      }
      case "Enter": {
        event.preventDefault();
        if (activeIndex >= 0 && activeIndex < results.length) {
          onSelect(results[activeIndex]);
          setShowResults(false);
          setActiveIndex(-1);
        }
        break;
      }
      case "Escape": {
        event.preventDefault();
        setShowResults(false);
        setActiveIndex(-1);
        break;
      }
    }
  }

  return (
    <div className="relative" ref={containerRef}>
      <input
        role="combobox"
        aria-expanded={visible && results.length > 0}
        aria-controls={listboxId}
        aria-activedescendant={activeOptionId}
        aria-autocomplete="list"
        placeholder="Search cards..."
        value={search}
        onChange={(event) => {
          setSearch(event.target.value);
          setShowResults(true);
          setActiveIndex(-1);
        }}
        onFocus={() => setShowResults(true)}
        onBlur={(event) => {
          if (!containerRef.current?.contains(event.relatedTarget)) {
            setShowResults(false);
            setActiveIndex(-1);
          }
        }}
        onKeyDown={handleKeyDown}
        className="border-input bg-background placeholder:text-muted-foreground focus:ring-ring h-7 w-44 rounded-md border px-2 text-xs focus:ring-1 focus:outline-none"
      />
      {visible && results.length > 0 && (
        <div
          ref={listRef}
          id={listboxId}
          role="listbox"
          className="bg-popover absolute top-full right-0 z-50 mt-1 max-h-60 w-max min-w-full overflow-y-auto rounded-md border shadow-md"
        >
          {results.map((card, resultIndex) => (
            <button
              key={card.cardId}
              id={`${listboxId}-option-${resultIndex}`}
              role="option"
              aria-selected={resultIndex === activeIndex}
              type="button"
              className={cn(
                "flex w-full items-center gap-2 px-3 py-1.5 text-left text-xs",
                resultIndex === activeIndex ? "bg-muted" : "hover:bg-muted",
              )}
              onMouseDown={(event) => event.preventDefault()}
              onMouseEnter={() => setActiveIndex(resultIndex)}
              onClick={() => {
                onSelect(card);
                setShowResults(false);
                setActiveIndex(-1);
              }}
            >
              <span className="truncate font-medium">{card.cardName}</span>
              <span className="text-muted-foreground shrink-0">{card.shortCode}</span>
            </button>
          ))}
        </div>
      )}
      {visible && results.length === 0 && (
        <div
          id={listboxId}
          role="listbox"
          className="bg-popover absolute top-full right-0 z-50 mt-1 w-full rounded-md border px-3 py-2 shadow-md"
        >
          <p className="text-muted-foreground text-xs">No matching cards</p>
        </div>
      )}
    </div>
  );
}

/**
 * Filters printings by query and deduplicates to unique cards.
 * @returns ResolvedCard array with one entry per unique card.
 */
function deduplicateToCards(allPrintings: Printing[], query: string): ResolvedCard[] {
  const lower = query.toLowerCase();
  const seen = new Set<string>();
  const results: ResolvedCard[] = [];

  for (const printing of allPrintings) {
    if (seen.has(printing.cardId)) {
      continue;
    }
    if (
      printing.card.name.toLowerCase().includes(lower) ||
      printing.shortCode.toLowerCase().includes(lower)
    ) {
      seen.add(printing.cardId);
      results.push({
        cardId: printing.cardId,
        cardName: printing.card.name,
        cardType: printing.card.type,
        superTypes: printing.card.superTypes,
        domains: printing.card.domains,
        shortCode: printing.shortCode,
        preferredPrintingId: null,
      });
    }
  }

  return results;
}
